import type { Locale } from "@/lib/site";

const commonKeywords = [
  "VibeAround",
  "AI coding agent",
  "AI coding agents",
  "AI coding assistant",
  "AI code assistant",
  "coding assistant",
  "agentic coding",
  "vibe coding",
  "AI developer tools",
  "local AI coding",
  "local AI coding",
  "remote coding",
  "remote development",
  "mobile coding",
  "developer workspace",
  "agent workspace",
];

const localeKeywords = {
  en: [
    "Codex CLI",
    "Claude Code",
    "Gemini CLI",
    "OpenCode",
    "terminal coding agent",
    "local coding agent",
    "AI agent desktop app",
    "AI coding desktop app",
    "mobile coding workflow",
    "coding agent orchestration",
    "multi-agent coding",
    "LLM provider routing",
  ],
  zh: [
    "AI 编程 Agent",
    "AI 编程助手",
    "AI 代码助手",
    "编程智能体",
    "代码智能体",
    "AI Agent 工作台",
    "AI Agent 控制台",
    "本地优先",
    "本地 AI 编程",
    "远程编程",
    "远程开发",
    "手机远程控制",
    "手机编程工作流",
    "Codex CLI",
    "Claude Code",
  ],
} satisfies Record<Locale, string[]>;

const docKeywords: Record<Locale, Record<string, string[]>> = {
  en: {
    index: [
      "VibeAround docs",
      "AI coding agent workspace documentation",
      "AI coding assistant documentation",
      "agentic coding workspace docs",
      "local AI agent manual",
      "remote AI coding documentation",
      "AI developer tools documentation",
    ],
    "quick-start": [
      "VibeAround quick start",
      "install AI coding agent workspace",
      "start local AI agent session",
      "start AI coding assistant",
      "first AI coding agent workflow",
      "agentic coding quick start",
    ],
    installation: [
      "VibeAround install",
      "install VibeAround macOS",
      "install VibeAround Windows",
      "install VibeAround Linux",
      "AI coding agent setup",
      "AI coding assistant setup",
      "local coding agent setup",
    ],
    download: [
      "VibeAround download",
      "VibeAround latest release",
      "AI coding agent desktop download",
      "AI coding assistant desktop app",
      "agentic coding desktop app",
      "VibeAround macOS Windows Linux",
    ],
    "migration-0-6": [
      "VibeAround migration",
      "upgrade VibeAround 0.7",
      "migrate local agent workspace",
      "VibeAround 0.6 to 0.7",
      "AI coding workspace migration",
    ],
    "why-vibearound": [
      "why use VibeAround",
      "AI coding agent workflow problem",
      "local agent workspace",
      "AI coding agents side by side",
      "agentic coding workflow",
      "multi-agent coding workflow",
      "AI developer workflow",
    ],
    "remote-coding": [
      "remote coding with local AI agents",
      "remote control coding agent",
      "continue coding from phone",
      "control coding agent from phone",
      "AI coding from phone",
      "local workspace remote access",
      "local session remote access",
      "remote development with AI agents",
      "cloud IDE alternative",
      "keep code local remote coding",
    ],
    "codex-mobile": [
      "Codex CLI from phone",
      "Codex mobile workflow",
      "remote Codex CLI",
      "control Codex from mobile",
      "Codex mobile access",
      "Codex remote control",
      "Codex app mobile",
      "Codex CLI remote access",
      "monitor Codex from phone",
      "Codex browser terminal",
    ],
    "codex-remote": [
      "Codex remote access",
      "Codex remote connections",
      "Codex mobile setup",
      "Codex CLI remote comparison",
      "Codex local workflow",
      "Codex cloud workspace alternative",
      "Codex SSH alternative",
      "Codex Tailscale alternative",
    ],
    "claude-remote": [
      "Claude Code remote access",
      "Claude Code Remote Control",
      "Claude Code from phone",
      "Claude Code mobile",
      "control Claude Code from phone",
      "continue Claude Code session",
      "Claude Code local session",
      "Claude Code web vs local",
    ],
    "gemini-remote": [
      "Gemini CLI remote access",
      "Gemini CLI from phone",
      "remote Gemini CLI",
      "Gemini coding agent workflow",
      "control Gemini CLI from phone",
      "Gemini CLI local session",
    ],
    "opencode-remote": [
      "OpenCode remote access",
      "OpenCode from phone",
      "remote OpenCode",
      "OpenCode messaging workflow",
      "OpenCode mobile workflow",
      "OpenCode Telegram",
      "OpenCode Discord",
      "OpenCode local session",
    ],
    "claude-code-switcher": [
      "Claude Code provider switcher",
      "Claude Code API bridge",
      "switch Claude Code providers",
      "Claude Code model routing",
      "Claude Code custom API",
      "Claude Code OpenRouter",
      "Claude Code DeepSeek",
      "Claude Code third-party models",
      "Claude Code OpenAI compatible",
    ],
    "local-ai-switch": [
      "local AI provider switcher",
      "AI model switcher",
      "LLM provider switcher",
      "AI provider routing",
      "local model routing",
      "AI agent provider profiles",
      "multi-model coding agents",
      "switch AI models locally",
    ],
    "agent-launch": [
      "AI agent launcher",
      "AI coding agent launcher",
      "launch Claude Code Codex Gemini OpenCode",
      "AI coding agent desktop launcher",
      "agent session launcher",
      "coding assistant launcher",
      "choose model before launch",
    ],
    "unified-workspace": [
      "AI coding agent workspace",
      "AI agent workspace",
      "AI coding workspace",
      "multi agent desktop workspace",
      "agentic coding workspace",
      "unified AI agent dashboard",
      "manage multiple coding agents",
      "AI agent control panel",
    ],
    "session-handover": [
      "AI agent session handover",
      "continue coding session",
      "handover local agent session",
      "mobile session continuation",
      "continue AI coding from phone",
      "cross-device coding session",
      "agent session continuity",
    ],
    "remote-messaging-terminal": [
      "remote coding terminal",
      "AI coding agent web terminal",
      "control coding agent from messaging",
      "Telegram Discord Slack AI agent",
      "AI agent messaging bot",
      "AI coding bot",
      "remote terminal for AI agents",
      "Lark Feishu AI agent",
    ],
    "live-preview": [
      "AI coding live preview",
      "preview local dev server remotely",
      "mobile web preview coding agent",
      "share local preview link",
      "agent generated artifact preview",
      "remote preview local development",
      "preview AI generated code",
    ],
    "provider-profiles": [
      "AI provider profiles",
      "OpenAI compatible API bridge",
      "Anthropic API bridge",
      "Gemini API bridge",
      "model provider switcher",
      "LLM API bridge",
      "AI API gateway",
      "custom LLM endpoint",
      "OpenRouter DeepSeek provider profile",
      "model alias routing",
    ],
    providers: [
      "supported AI model providers",
      "OpenAI Anthropic Gemini DeepSeek providers",
      "AI coding provider support",
      "custom AI endpoint",
      "OpenAI compatible providers",
      "OpenRouter provider",
      "Azure OpenAI provider",
      "local LLM endpoint",
    ],
    channels: [
      "AI agent messaging channels",
      "Telegram AI coding agent",
      "Slack AI coding agent",
      "Discord AI coding agent",
      "Feishu Lark AI agent",
      "DingTalk AI agent",
      "WeCom AI agent",
      "messaging app remote control",
    ],
    "local-security": [
      "local AI agent security",
      "AI coding agent security",
      "remote coding security",
      "local workspace privacy",
      "AI agent tunnel safety",
      "keep code local AI",
      "AI coding privacy",
      "remote terminal security",
      "provider data privacy",
    ],
    "supported-agents": [
      "supported AI coding agents",
      "Claude Code Codex Gemini OpenCode",
      "AI agent compatibility",
      "coding agent list",
      "AI coding assistant compatibility",
      "supported coding assistants",
      "agent CLI compatibility",
    ],
    architecture: [
      "VibeAround architecture",
      "local agent architecture",
      "AI coding workspace architecture",
      "API bridge architecture",
      "remote agent control architecture",
      "local session architecture",
      "AI agent orchestration architecture",
    ],
    "develop-locally": [
      "VibeAround local development",
      "develop VibeAround website",
      "VibeAround contributor setup",
      "AI agent workspace development",
      "AI developer tool local development",
    ],
    troubleshooting: [
      "VibeAround troubleshooting",
      "AI coding agent troubleshooting",
      "remote coding not working",
      "provider profile troubleshooting",
      "Codex remote not working",
      "Claude Code remote not working",
      "Web Terminal connection issue",
      "AI provider switcher not working",
    ],
  },
  zh: {
    index: [
      "VibeAround 文档",
      "AI 编程 Agent 工作空间文档",
      "AI 编程助手文档",
      "本地 AI Agent 手册",
      "远程编程文档",
      "AI Agent 工作台说明",
    ],
    "quick-start": [
      "VibeAround 快速开始",
      "AI 编程 Agent 入门",
      "AI 编程助手入门",
      "本地 Agent 会话启动",
      "第一次使用 VibeAround",
      "本地 AI 编程工作流",
    ],
    installation: [
      "VibeAround 安装",
      "VibeAround macOS 安装",
      "VibeAround Windows 安装",
      "VibeAround Linux 安装",
      "AI 编程助手安装",
      "AI Agent 工作台安装",
    ],
    download: [
      "VibeAround 下载",
      "VibeAround 最新版本",
      "AI 编程 Agent 桌面端下载",
      "AI 编程助手桌面版",
      "VibeAround 安装包",
      "VibeAround Mac Windows Linux",
    ],
    "migration-0-6": [
      "VibeAround 迁移",
      "升级 VibeAround 0.7",
      "VibeAround 0.6 升级",
      "本地 Agent 工作空间迁移",
      "AI 编程工具升级",
    ],
    "why-vibearound": [
      "为什么需要 VibeAround",
      "AI 编程 Agent 工作流",
      "AI 编程助手工作流",
      "本地 Agent 工作空间",
      "多个 AI Agent 并行",
      "多 Agent 协作开发",
    ],
    "remote-coding": [
      "远程编程",
      "远程开发",
      "远程控制 AI 编程 Agent",
      "手机远程控制电脑编程",
      "手机继续编程",
      "本地工作空间远程访问",
      "本地会话远程访问",
      "云 IDE 替代",
      "代码不搬到云端",
    ],
    "codex-mobile": [
      "Codex CLI 手机",
      "Codex 手机工作流",
      "手机控制 Codex",
      "手机远程控制 Codex",
      "iPhone 访问 Codex CLI",
      "远程 Codex CLI",
      "Codex 浏览器终端",
      "手机查看 Codex 进度",
      "电脑上的 Codex CLI",
    ],
    "codex-remote": [
      "Codex 远程访问",
      "Codex 远程控制",
      "Codex CLI 远程对比",
      "Codex 本地工作流",
      "Codex 云工作空间替代",
      "Codex SSH Tailscale 对比",
      "Codex 手机端和 CLI",
    ],
    "claude-remote": [
      "Claude Code 远程访问",
      "Claude Code 远程控制",
      "Claude Code Remote Control",
      "手机使用 Claude Code",
      "手机控制 Claude Code",
      "继续 Claude Code 会话",
      "Claude Code 本地会话",
      "Claude Code 浏览器继续",
    ],
    "gemini-remote": [
      "Gemini CLI 远程访问",
      "Gemini CLI 远程控制",
      "手机使用 Gemini CLI",
      "远程 Gemini CLI",
      "Gemini 编程 Agent 工作流",
      "Gemini CLI 本地会话",
    ],
    "opencode-remote": [
      "OpenCode 远程访问",
      "OpenCode 远程控制",
      "手机使用 OpenCode",
      "远程 OpenCode",
      "OpenCode 消息频道",
      "OpenCode Telegram",
      "OpenCode Discord",
      "OpenCode 本地会话",
    ],
    "claude-code-switcher": [
      "Claude Code Provider Switcher",
      "Claude Code API Bridge",
      "Claude Code 模型切换",
      "Claude Code 切换模型",
      "Claude Code 第三方模型",
      "Claude Code 接入 DeepSeek",
      "Claude Code 接入 OpenRouter",
      "Claude Code Provider 路由",
      "Claude Code 自定义 API",
    ],
    "local-ai-switch": [
      "本地 AI 切换",
      "AI 模型切换",
      "AI Provider 切换",
      "本地模型路由",
      "模型路由",
      "多模型切换",
      "AI Agent Provider Profile",
    ],
    "agent-launch": [
      "AI Agent 启动器",
      "AI 编程助手启动器",
      "启动 Claude Code Codex Gemini OpenCode",
      "AI 编程 Agent 桌面启动器",
      "Agent Session 启动",
      "选择模型启动 Agent",
    ],
    "unified-workspace": [
      "AI 编程 Agent 工作空间",
      "AI Agent 工作台",
      "AI Agent 控制台",
      "多 Agent 桌面工作空间",
      "统一 AI Agent Dashboard",
      "管理多个编程 Agent",
      "多 Agent 并行开发",
    ],
    "session-handover": [
      "AI Agent 会话接续",
      "继续编程会话",
      "本地 Agent Session Handover",
      "手机继续会话",
      "跨设备继续 AI 会话",
      "电脑手机接力编程",
    ],
    "remote-messaging-terminal": [
      "远程编程终端",
      "AI 编程 Agent Web Terminal",
      "消息控制 AI Agent",
      "飞书控制 AI Agent",
      "Telegram 控制 AI Agent",
      "企业微信控制 AI Agent",
      "钉钉控制 AI Agent",
      "Discord Slack AI Agent",
    ],
    "live-preview": [
      "AI 编程实时预览",
      "远程预览本地 dev server",
      "手机预览 Agent 产物",
      "分享本地预览链接",
      "预览本地开发服务",
      "手机查看前端预览",
    ],
    "provider-profiles": [
      "AI Provider Profile",
      "AI Provider 配置",
      "OpenAI 兼容接口",
      "OpenAI compatible API Bridge",
      "Anthropic API Bridge",
      "Gemini API Bridge",
      "模型 Provider 切换",
      "自定义 API Endpoint",
      "API 请求转换",
      "多模型 Provider 管理",
    ],
    providers: [
      "支持的 AI Provider",
      "OpenAI Anthropic Gemini DeepSeek Provider",
      "AI 编程 Provider 支持",
      "DeepSeek 接入 Agent 工具",
      "OpenRouter 接入 Claude Code",
      "自定义 AI Endpoint",
      "OpenAI 兼容模型",
    ],
    channels: [
      "AI Agent 消息频道",
      "消息应用控制 AI Agent",
      "Telegram AI 编程 Agent",
      "飞书 AI 编程 Agent",
      "企业微信 AI Agent",
      "钉钉 AI Agent",
      "Slack AI 编程 Agent",
      "Discord AI 编程 Agent",
      "Lark AI Agent",
    ],
    "local-security": [
      "本地优先 AI 安全",
      "AI 编程 Agent 安全",
      "远程编程安全",
      "本地工作空间隐私",
      "代码不上传云端",
      "本地运行 AI Agent",
      "AI Agent Tunnel 安全",
      "远程终端安全",
      "模型 Provider 隐私",
    ],
    "supported-agents": [
      "支持的 AI 编程 Agent",
      "Claude Code Codex Gemini OpenCode",
      "AI Agent 兼容性",
      "编程 Agent 列表",
      "支持哪些 AI 编程助手",
      "AI 编程工具支持",
    ],
    architecture: [
      "VibeAround 架构",
      "本地优先 Agent 架构",
      "AI 编程工作空间架构",
      "API Bridge 架构",
      "远程控制架构",
      "本地会话架构",
    ],
    "develop-locally": [
      "VibeAround 本地开发",
      "开发 VibeAround 网站",
      "VibeAround 贡献者设置",
      "AI Agent 工作空间开发",
      "文档网站本地开发",
    ],
    troubleshooting: [
      "VibeAround 排障",
      "AI 编程 Agent 排障",
      "远程编程无法使用",
      "手机连接不上 Agent",
      "Provider Profile 排障",
      "模型切换失败",
      "Web Terminal 连接失败",
      "Tunnel 访问失败",
    ],
  },
};

export function docSeoKeywords(locale: Locale, slugs: string[] | undefined) {
  const slug = slugs && slugs.length > 0 ? slugs.join("/") : "index";
  const pageKeywords = docKeywords[locale][slug] ?? [];

  return [...new Set([...commonKeywords, ...localeKeywords[locale], ...pageKeywords])];
}
